apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" .Release.Name .Values.mysql.initConfigMapName }}
  labels:
    app: {{ printf "%s-mysql" .Release.Name }}
data:
  init.sql: |-
{{ .Files.Get "mysql-init.sql" | indent 4 }}