apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env
          image: mysql:latest
          name: mysql
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/db.sql
              name: mysql-cm0
              subPath: db.sql
            - mountPath: /var/lib/mysql
              name: mysql-data
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: init.sql
                path: db.sql
            name: mysql-cm0
          name: mysql-cm0
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data
