apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-mysql-data" .Release.Name }}
  labels:
    app: {{ printf "%s-mysql-data" .Release.Name }}
spec:
  accessModes:
    - {{ .Values.mysql.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}