apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-mysql" .Release.Name }}
  labels:
    app: {{ printf "%s-mysql" .Release.Name }}
spec:
  type: {{ .Values.mysql.service.type }}
  selector:
    app: {{ printf "%s-mysql" .Release.Name }}
  ports:
    - name: mysql
      port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.targetPort }}