apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-grafana-data" .Release.Name }}
  labels:
    app: {{ printf "%s-grafana-data" .Release.Name }}
spec:
  accessModes:
    - {{ .Values.grafana.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}