apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-grafana-admin" .Release.Name }}
  labels:
    app: {{ printf "%s-grafana" .Release.Name }}
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: "{{ .Values.grafana.adminUser }}"
  GF_SECURITY_ADMIN_PASSWORD: "{{ .Values.grafana.adminPassword }}"