apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-mysql-passwords" .Release.Name }}
  labels:
    app: {{ printf "%s-mysql" .Release.Name }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.databaseName | quote }}
  MYSQL_USER: {{ .Values.mysql.userName | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.userPassword | quote }}