apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-prom-data" .Release.Name }}
  labels:
    app: {{ printf "%s-prom-data" .Release.Name }}
spec:
  accessModes:
    - {{ .Values.prometheus.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.prometheus.persistence.size }}