apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-prometheus" .Release.Name }}
  labels:
    app: {{ printf "%s-prometheus" .Release.Name }}
spec:
  type: {{ .Values.prometheus.service.type }}
  selector:
    app: {{ printf "%s-prometheus" .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.prometheus.service.port }}
      targetPort: {{ .Values.prometheus.service.targetPort }}