# Redis Master
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: redis
    spec:
      containers:
        - env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: REDIS_AOF_ENABLED
              value: "no"
            - name: REDIS_DISABLE_COMMANDS
              value: FLUSHDB,FLUSHALL,CONFIG
            - name: REDIS_REPLICATION_MODE
              value: master
          image: bitnami/redis:latest
          name: redis
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /bitnami/redis/data
              name: redis-data
      restartPolicy: Always
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data

---
# Redis Slave
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: redis-slave
  name: redis-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-slave
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: redis-slave
    spec:
      containers:
        - env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: REDIS_AOF_ENABLED
              value: "no"
            - name: REDIS_MASTER_HOST
              value: redis
            - name: REDIS_REPLICATION_MODE
              value: slave
          image: bitnami/redis:latest
          name: redis-slave
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always

---
# Redis Sentinel 1
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: redis-sentinel-1
  name: redis-sentinel-1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-sentinel-1
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: redis-sentinel-1
    spec:
      containers:
        - env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: REDIS_AOF_ENABLED
              value: "no"
            - name: REDIS_SENTINEL_RESOLVE_HOSTNAMES
              value: "yes"
          image: bitnami/redis-sentinel:latest
          name: redis-sentinel-1
          ports:
            - containerPort: 26379
              protocol: TCP
      hostname: redis-sentinel-1
      restartPolicy: Always

---
# Redis Sentinel 2
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: redis-sentinel-2
  name: redis-sentinel-2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-sentinel-2
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: redis-sentinel-2
    spec:
      containers:
        - env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: REDIS_AOF_ENABLED
              value: "no"
            - name: REDIS_SENTINEL_RESOLVE_HOSTNAMES
              value: "yes"
          image: bitnami/redis-sentinel:latest
          name: redis-sentinel-2
          ports:
            - containerPort: 26380
              protocol: TCP
      hostname: redis-sentinel-2
      restartPolicy: Always

---
# Redis Sentinel 3
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: redis-sentinel-3
  name: redis-sentinel-3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-sentinel-3
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: redis-sentinel-3
    spec:
      containers:
        - env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: REDIS_AOF_ENABLED
              value: "no"
            - name: REDIS_SENTINEL_RESOLVE_HOSTNAMES
              value: "yes"
          image: bitnami/redis-sentinel:latest
          name: redis-sentinel-3
          ports:
            - containerPort: 26381
              protocol: TCP
      hostname: redis-sentinel-3
      restartPolicy: Always

---
# Redis Insight
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: redis-insight
  name: redis-insight
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-insight
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: redis-insight
    spec:
      containers:
        - image: redislabs/redisinsight:latest
          name: redis-insight
          ports:
            - containerPort: 5540
              protocol: TCP
          volumeMounts:
            - mountPath: /db
              name: redis-insight-data
      hostname: redis-insight
      restartPolicy: Always
      volumes:
        - name: redis-insight-data
          persistentVolumeClaim:
            claimName: redis-insight-data
