apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-redis-sentinel-headless" .Release.Name }}
  labels:
    app: {{ printf "%s-redis-sentinel" .Release.Name }}
spec:
  clusterIP: None
  selector:
    app: {{ printf "%s-redis-sentinel" .Release.Name }}
  ports:
    - name: sentinel
      port: {{ .Values.redis.sentinel.port }}
      targetPort: {{ .Values.redis.sentinel.port }}
