apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-redis-master" .Release.Name }}
  labels:
    app: {{ printf "%s-redis-master" .Release.Name }}
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    app: {{ printf "%s-redis-master" .Release.Name }}
  ports:
    - name: master
      port: {{ .Values.redis.service.masterPort }}
      targetPort: {{ .Values.redis.service.masterPort }}