# Redis Master Service
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: redis

---
# Redis Slave Service
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: redis-slave
  name: redis-slave
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: redis-slave

---
# Redis Sentinel 1
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: redis-sentinel-1
  name: redis-sentinel-1
spec:
  ports:
    - name: "26379"
      port: 26379
      targetPort: 26379
  selector:
    io.kompose.service: redis-sentinel-1

---
# Redis Sentinel 2
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: redis-sentinel-2
  name: redis-sentinel-2
spec:
  ports:
    - name: "26380"
      port: 26380
      targetPort: 26380
  selector:
    io.kompose.service: redis-sentinel-2

---
# Redis Sentinel 3
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: redis-sentinel-3
  name: redis-sentinel-3
spec:
  ports:
    - name: "26381"
      port: 26381
      targetPort: 26381
  selector:
    io.kompose.service: redis-sentinel-3

---
# Redis Insight
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: redis-insight
  name: redis-insight
spec:
  ports:
    - name: "5540"
      port: 5540
      targetPort: 5540
  selector:
    io.kompose.service: redis-insight



