apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-redis-slave" .Release.Name }}
  labels:
    app: {{ printf "%s-redis-slave" .Release.Name }}
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    app: {{ printf "%s-redis-slave" .Release.Name }}
  ports:
    - name: slave
      port: {{ .Values.redis.service.slavePort }}
      targetPort: {{ .Values.redis.service.slavePort }}