apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-redis-insight" .Release.Name }}
  labels:
    app: {{ printf "%s-redis-insight" .Release.Name }}
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    app: {{ printf "%s-redis-insight" .Release.Name }}
  ports:
    - name: insight
      port: {{ .Values.redis.service.insightPort }}
      targetPort: {{ .Values.redis.service.insightPort }}