apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-gateway-tcp
  labels:
    app: {{ .Release.Name }}-api-gateway-tcp
spec:
  type: {{ .Values.apiGateway.service.type }}
  selector:
    app: {{ .Release.Name }}-api-gateway
  ports:
    - name: tcp
      port: {{ .Values.apiGateway.service.port }}
      targetPort: {{ .Values.apiGateway.service.targetPort }}