apiGateway:
  replicaCount: 1
  image:
    repository: localhost:5000/api-gateway
    tag: latest
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 8000
    targetPort: 8000
  externalUrl: /api

mysql:
  replicaCount: 1
  image:
    repository: mysql
    tag: "8"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3306
    targetPort: 3306
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 100Mi
  initConfigMapName: mysql-init

grafana:
  replicaCount: 1
  image:
    repository: grafana/grafana
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 100Mi
  path: "http://localhost/grafana"

prometheus:
  replicaCount: 1
  image:
    repository: prom/prometheus
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9090
    targetPort: 9090
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 100Mi
  ingressPath: /prometheus
  externalUrl: /prometheus

redis:
  replicaCount: 1              # Master replica
  master:
    port: 6379
  slave:
    replicaCount: 1            # Slave replica
  sentinel:
    replicaCount: 3
    port: 26379
    quorum: 2
  insight:
    replicaCount: 1            # Redis Insight instance
  image:
    repository: bitnami/redis
    tag: latest
    pullPolicy: IfNotPresent
  sentinelImage:
    repository: bitnami/redis-sentinel
    tag: latest
    pullPolicy: IfNotPresent
  insightImage:
    repository: redislabs/redisinsight
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    masterPort: 6379
    slavePort: 6379
    insightPort: 5540
  persistence:
    master:
      enabled: true
      accessMode: ReadWriteOnce
      size: 100Mi
    insight:
      enabled: true
      accessMode: ReadWriteOnce
      size: 100Mi
  env:
    allowEmptyPassword: "yes"
    aofEnabled: "no"
    disableCommands: "FLUSHDB,FLUSHALL,CONFIG"

ingress:
  enabled: true
  className: nginx
  annotations: {}
  host: localhost
  rewritePaths:
    - path: /api$
      pathType: ImplementationSpecific
      service:
        name: api-gateway-tcp
        port: 8000
    - path: /api/(?!swagger)(.*)
      pathType: ImplementationSpecific
      service:
        name: api-gateway-tcp
        port: 8000
  prefixPaths:
    - path: /api/swagger
      pathType: Prefix
      service:
        name: api-gateway-tcp
        port: 8000
    - path: /grafana
      pathType: Prefix
      service:
        name: grafana
        port: 3000
    # if you want to expose prometheus via ingress, uncomment this part
    #- path: /prometheus
    #  pathType: Prefix
    #  service:
    #    name: prometheus
    #    port: 9090
  tls: []

loki-stack:
  loki:
    enabled: true
    # override the default image tag to a version >= 2.9.7
    image:
      repository: grafana/loki
      tag:       "2.9.7"
    # (optional) if you still want to tune or disable probes,
    # you can keep your readinessProbe/livenessProbe overrides here
  promtail:
    enabled: true
    # explicitly tell Promtail where to push logs:
    config:
      clients:
          - url: "http://gofiber-starter-stack-loki:3100/loki/api/v1/push"
  grafana:
    enabled: false